# Generated by Django 2.2.9 on 2020-01-09 13:33
from django.db import migrations, models


# def forward():
#     Student = apps.get_model('students', 'Student')
#     for student in Student.objects.all().only('id', 'phone').iterator():
#         numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#
#         a = student.phone
#         b = ""
#         for i in a:
#             if i in numbers:
#                 b.join(i)
#
#         student.phone = ''.join(b)
#         student.save(update_fields=['phone'])


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.RunPython(forward()),

        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('emails', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
    ]
