# Generated by Django 2.2.9 on 2020-01-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0002_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='groups.Group'),
        ),
    ]
