# Generated by Django 2.2.9 on 2020-01-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200125_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emails',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
