# Generated by Django 2.2.9 on 2020-01-19 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='birth_date',
        ),
    ]
