# Generated by Django 2.2.9 on 2020-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teachers', '0002_remove_teacher_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_group',
        ),
    ]
