# Generated by Django 2.2.9 on 2020-01-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0003_student_group_id'),
        ('teachers', '0002_remove_teacher_birth_date'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='senior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='students.Student'),
        ),
    ]
